name: test

on: push

jobs:
  command:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set-up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Check current directory on windows
        run: Test-Path D:\a\vscode-extension-exercise\vscode-extension-exercise/test-workspace/djangoApp/views.py
        if: runner.os == 'Windows'
      - name: Check current directory on mac or linux
        run: '[ -e "/Users/runner/work/vscode-extension-exercise/vscode-extension-exercise/test-workspace/djangoApp/views.py" ] && echo true || echo false'
        if: runner.os != 'Windows'
      - run: npm ci
      - name: Run test on linux
        run: xvfb-run -a npm run test
        if: runner.os == 'Linux'
      - name: Run test on Mac or Windows
        run: npm run test
        if: runner.os != 'Linux'
