name: test

on: push

jobs:
  command:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # `actions/checkout@v4`を実行
      - name: Checkout
        uses: actions/checkout@v4
        # `actions/setup-node@v4`を実行
      - name: set-up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Check current directory on windows
        run: cd
        if: runner.os == 'Windows'
      - name: Check current directory on mac or linux
        run: pwd
        if: runner.os != 'Windows'
      - run: npm ci
      - name: Run test on linux
        run: xvfb-run -a npm run test
        if: runner.os == 'Linux'
      - name: Run test on Mac or Windows
        run: npm run test
        if: runner.os != 'Linux'
